### ISSUE TITLE
Name this package

### ISSUE THREAD

**Issue by davidagold** [davidagold/StructuredQueries.jl#8]
A number of people have suggested this package ought to be renamed. @dmbates gives a good summary of the justification [here](https://github.com/JuliaStats/DataFrames.jl/pull/1008#issuecomment-236199622). That was always the plan. I suppose it ought to happen sooner rather than later. So! Suggestions are more than welcome in this thread.

**Comment by ararslan** [comment]
> The name alludes to Hadley's notion of dplyr as a "grammar of data manipulation", rather than a specific design spec.

DataGrammar.jl? ¯\_(ツ)_/¯

**Comment by nalimilan** [comment]
Not a big fan of DataGrammar, which sounds a bit obscure for newcomers. DataManagement? DataQueries? DataTools? DataFlows? Plus the same series replacing Data with Tables.

We could also imagine merging the package into DataStreams when it's ready.

**Comment by davidagold** [comment]
I prefer Select.jl over all of these.

Why should this go into DataStreams? 

Edit: Queries.jl would be nice, too. Or Inquire.jl.
Double edit: Just realized "inquire" rhymes with "dplyr", which makes me like it even more =p

**Comment by dmbates** [comment]
`select` already has a meaning in base Julia

```
help?> select
search: select select! selectperm selectperm! set_bigfloat_precision

  select(v, k, [by=<transform>,] [lt=<comparison>,] [rev=false])

  Variant of select! which copies v before partially sorting it, thereby returning the same thing as select! but
  leaving v unmodified.

julia> methods(select)
# 1 method for generic function "select":
select(v::AbstractArray{T,1}, k::Union{Int64,OrdinalRange{T,S}}) at sort.jl:69
```

**Comment by ararslan** [comment]
I think @milktrader had some ideas. Now's your time to shine!

**Comment by davidagold** [comment]
@dmbates Can you pun a Base method with a package name? I never really thought that an issue. In any case, your logic applies even more so to the actual command `@select` we export from this package, but I don't intend on renaming that. (Though similar packages in other languages call such a manipulation `project`, which I don't mind.)

**Comment by milktrader** [comment]
Okay, since this is on topic. I've got a clever name in mind and maybe it can generate some other ideas if nothing else.

Mercury.jl

Mercury is used to pull gold from rocks.

**Comment by milktrader** [comment]
There is precedence for naming packages after elements from the periodic table:   

[Gallium.jl](https://github.com/Keno/Gallium.jl)

Can't remember where Mercury and Gold fit in the periodic table?

![screen shot 2016-07-30 at 7 19 15 pm](https://cloud.githubusercontent.com/assets/324836/17273645/b9fa68f6-568a-11e6-9e24-89d4777ca297.png)

**Comment by nalimilan** [comment]
I'd prefer a more explicit name (Gallium itself might be a temporary name until the debugger is finished). Select.jl has the drawback that it's only the name of one operation, and there's much more in the package.

> Why should this go into DataStreams?

@davidagold Because they both provide backend-agnostic support for working with data. But that was just a suggestion.

**Comment by davidagold** [comment]
@nalimilan Though `select` is representative of querying on the whole -- in SQL, the other commands represented in this package are clauses of a `SELECT` statement. Of course, this is all modulo two-table commands, e.g. `join`, which I do intend to support. (But maybe they go in `Join.jl` =p)

I think the functionality provided here is sufficiently different from that in DataStreams that they warrent different packages. The strategy DataStreams takes towards backend agnostic-ness is also quite different.

@milktrader I think Mercury may be too easily confused as relating to the Mercurial SCM. =/

**Comment by johnmyleswhite** [comment]
RelationalAlgebra.jl is probably the name that most closely represents the goals of the package as I understand them.

**Comment by davidagold** [comment]
@johnmyleswhite though that's also kind of obscure to folks of different backgrounds. I guess that doesn't matter so much if the package is included in `DataFrames` or whatever tabular data package folks will be using.

**Comment by johnmyleswhite** [comment]
If your goal is to ensure no one expects too much from your work, giving it an obscure name seems like a good strategy.

**Comment by garborg** [comment]
Relational algebra seems right for the core common API, so it's great to hear that's in the works.

I don't know of a term for 'relational algebra as applicable to tables' (tables not being 'relations'), but people mostly talk about it in relation to tables, so the name evokes tables just fine.

**Comment by bramtayl** [comment]
PanQuery? Or AbstractQuery?

**Comment by richardreeve** [comment]
I certainly agree that the name needs to be changed, and I think the less obscure the better (so I would also vote against element-related names), but I'm not sure why we wouldn't include this in AbstractTables.jl as the standard interface for anything derived from AbstractTable... or are we planning on having multiple standard query interfaces to tables?

I'm not sure what they would look like, but If so, I would vote for something tying this conceptually to SQL, so StructuredQuery.jl, since that's how I see this interface. I would honestly see it as the standard though, and so folded into AbstractTables.jl.

**Comment by maxlarsen** [comment]
Maybe
DataManipulation.jl 
?

**Comment by nalimilan** [comment]
It's important to note here that LINQ.jl is now called Query.jl. Unless the packages are merged at some point, we need to find a distinct enough name for jplyr.

**Comment by davidanthoff** [comment]
Maybe something with "Data" in the name? In my mind the "Data" term in the julia ecosystem generally points towards data that roughly has column/row shape, and I believe jplyr is meant to work with that kind of data, right? Query.jl, on the other hand, is meant for anything in rows, including things that don't have columns, for example lists of custom types or simple arrays etc. Or something with "Table" in the name?

**Comment by davidagold** [comment]
I'm going to close and lock this issue until the development of this package has reached a more mature stage.

EDIT: I will say that I appreciate everybody's input. I just don't think this is an appropriate time for this discussion.

**Comment by davidagold** [comment]
Okay. Having factored out the backend-specific collection machinery into [AbstractTables](https://github.com/davidagold/AbstractTables.jl) and [SQLQuery (WIP)](https://github.com/yeesian/SQLQuery.jl/pull/2), I think the goals and methodology of this package have been made clearer. This package provides a backend-agnostic framework for representing queries against arbitrary data sources by means of the `@query` macro and `Query{S}`/`QueryNode` type interfaces. Since this package provides a `Query` type, I think an appropriate name, following Julia convention, would be Queries. However, I'm also open to the argument that this name is too similar to that of @davidanthoff 's package, Query. I would also be open to naming this package something like StructuredQueries, since a `Query` essentially represents the structure of a query but does not guarantee any particular semantics. 

Thoughts people?

**Comment by davidanthoff** [comment]
I still feel that it would be good if the name included something that indicates that the package supports queries against table-like structures, i.e. things that have columns. That seems a major difference compared to Query.jl that users might care about when they initially look for a package with this functionality. There are obviously lots of implementation differences, but that might be of less interest to a user. Not sure whether something like "DataQueries" is any good, or whether "Data" is the right term, maybe "TableQueries" or something like that.

 I do think that having "Query" and "Queries" would not be ideal (and sorry for grabbing the name first!).

**Comment by davidagold** [comment]
@davidanthoff Again, this package doesn't guarantee any specific semantics -- it really just represents the structure of a query. It is entirely up to other packages to determine and implement the semantics of, e.g.

``` julia
@query source |>
    filter(...) |>
    select(...)
```

for specific types of `source`. As such, there are _no limitations_ on what types of objects can be sources to a `Query`. (EDIT: In particular, sources needn't be things with "columns".) If somebody thinks they can give consistent, sensible semantics to queries against an `Array` of structs, or against a graph, or against JSON-like documents, or against _whatever_, they can do that in a package that extends the present interface.

**Comment by davidanthoff** [comment]
Ah, then I had misunderstood the design, sorry. Well, then our two packages are really doing pretty much exactly the same thing, and maybe we should have named them Query1 and Query2 and thrown a dice who gets which name ;)

PS: Funnily enough, I had actually just added a JSON example to Query a couple of days ago.

**Comment by davidagold** [comment]
They are very similar, though not without differences. Your package appears to be more user-facing, whereas mine is aimed more at developers of packages that offer data structures amenable to some sort of querying logic.  Indeed, given that the present package doesn't itself implement any backend-specific functionality, I don't really intend for end-users to ever invoke `using jplyr` specifically. Packages that extend the present framework will reexport jplyr -- the only things visible to user will be `@query`/`@collect` and `Query{S}`, e.g.:

``` julia
julia> using Tables

julia> tbl = Tables.Table(
               name = ["Niamh", "Roger", "Genevieve", "Aiden"],
               age = [27, 63, 26, 17],
               eye_color = ["green", "brown", "brown", "blue"]
           )
Tables.Table
│ Row │ name        │ age │ eye_color │
├─────┼─────────────┼─────┼───────────┤
│ 1   │ "Niamh"     │ 27  │ "green"   │
│ 2   │ "Roger"     │ 63  │ "brown"   │
│ 3   │ "Genevieve" │ 26  │ "brown"   │
│ 4   │ "Aiden"     │ 17  │ "blue"    │


julia> @query tbl |>
           filter(age > 20)
Query with Tables.Table source
```

The `@query` macro and the resultant `Query{Table}` object are provided by jplyr, but that is all behind the scenes and largely invisible to the end user. It's possible that most future users of this functionality will not know the name of the present package. =p So I'm flexible on the name, but I would like it (i) to conform to Julia convention as much as possible and (ii) to reflect my goals with this project.

**Comment by davidanthoff** [comment]
My sense right now is that the `Queryable` part in [Query.jl](https://github.com/davidanthoff/Query.jl) probably corresponds most closely to the jplyr design (i.e. provide a source agnostic graph of query operations that each source can then provide collecting logic for). [Query.jl](https://github.com/davidanthoff/Query.jl) has two additional developer facing options/APIs for hooking data sources up, they essentially correspond to all the ways described in the [LINQ documentation](https://msdn.microsoft.com/en-us/library/mt693241.aspx).

Really too bad that we missed each other when I visited MIT in July, we would have had a lot of stuff to chat about... Do let me know if you are visiting the Bay Area at any point, though! I would like to understand the basic design principles of jplyr better, maybe it might make sense if we scheduled an online webinar like thing at some point where you present 30 minutes on jplyr, I present 30 minutes on Query, just so that the two of us (and anyone else interested) have a better understanding of the two packages?

**Comment by nalimilan** [comment]
If that's intended to developers only, it should be easier to find a name that isn't too close to Query.jl. Maybe QueryStructures (rather than StructuredQueries, according to your explanation)? Or QueryFramework, QueryEngine...

**Comment by bramtayl** [comment]
Two things. 1) I've deleted the PanQuery.jl package cause jplyr does everything better, so that name is open. 2) The `@chain_map` macro in the dev version of `ChainMap.jl` might be worth looking at. It combines vectorization, chaining, lifting, and column referencing into one macro.
